name: test react app
on: push
jobs:
  test_this_shit:
    run-on: ubuntu-latest
    steps:
      - name: Get reposetory code 
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: test app
        run: npm run test 